# Generated by Django 4.0.3 on 2022-04-30 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(blank=True, max_length=30, null=True)),
                ('q2', models.CharField(blank=True, max_length=30, null=True)),
                ('q3', models.CharField(blank=True, max_length=30, null=True)),
                ('q4', models.CharField(blank=True, max_length=30, null=True)),
                ('q5', models.CharField(blank=True, max_length=30, null=True)),
                ('q6', models.CharField(blank=True, max_length=30, null=True)),
                ('q7', models.CharField(blank=True, max_length=30, null=True)),
                ('q8', models.CharField(blank=True, max_length=30, null=True)),
                ('q9', models.CharField(blank=True, max_length=30, null=True)),
                ('q10', models.CharField(blank=True, max_length=30, null=True)),
                ('quiz_about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
