# Generated by Django 4.0.3 on 2022-04-30 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsetup',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 12, 54, 20, 282868, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='quizsetup',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quizsetup',
            name='q1',
            field=models.CharField(blank=True, help_text='Favourite hobby', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quizsetup',
            name='q10',
            field=models.CharField(blank=True, help_text='How many languages do you speak', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quizsetup',
            name='q2',
            field=models.CharField(blank=True, help_text='Favorite animal', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quizsetup',
            name='q3',
            field=models.CharField(blank=True, help_text='Which place would you visit', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quizsetup',
            name='q4',
            field=models.CharField(blank=True, help_text='Favourite thing to do', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quizsetup',
            name='q5',
            field=models.CharField(blank=True, help_text='Favourite genre of music', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quizsetup',
            name='q6',
            field=models.CharField(blank=True, help_text='Favourite food', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quizsetup',
            name='q7',
            field=models.CharField(blank=True, help_text='One thing you would like to do everyday', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quizsetup',
            name='q8',
            field=models.CharField(blank=True, help_text='Favourite movie', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quizsetup',
            name='q9',
            field=models.CharField(blank=True, help_text='Favourite series', max_length=30, null=True),
        ),
    ]
