# Generated by Django 4.0.3 on 2022-04-30 16:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_setup', '0002_quizsetup_created_quizsetup_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsetup',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 4, 30, 16, 17, 14, 436684, tzinfo=utc)),
        ),
    ]
