# Generated by Django 4.0.3 on 2022-04-30 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_setup', '0004_alter_quizsetup_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsetup',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 16, 20, 29, 615621, tzinfo=utc)),
        ),
    ]
