# Generated by Django 2.2.12 on 2022-06-13 20:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_setup', '0007_auto_20220613_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsetup',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 20, 6, 22, 855900, tzinfo=utc)),
        ),
    ]
