# Generated by Django 4.0.3 on 2022-05-04 20:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_setup', '0008_tmmasetup_created_on_tmmasetup_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsetup',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 20, 56, 4, 449823, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tmmasetup',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 20, 56, 4, 450823, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wordlesetup',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 20, 56, 4, 450823, tzinfo=utc)),
        ),
    ]
