# Generated by Django 4.0.3 on 2022-05-04 21:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_setup', '0009_alter_quizsetup_created_alter_tmmasetup_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TtmaSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(blank=True, help_text='1) I enjoy talking about: ', max_length=10, null=True)),
                ('q2', models.CharField(blank=True, help_text='2) I enjoy talking about: ', max_length=10, null=True)),
                ('q3', models.CharField(blank=True, help_text='3) I enjoy talking about: ', max_length=10, null=True)),
                ('q4', models.CharField(blank=True, help_text='4) I enjoy talking about: ', max_length=10, null=True)),
                ('q5', models.CharField(blank=True, help_text='5) I enjoy talking about: ', max_length=10, null=True)),
                ('q6', models.CharField(blank=True, help_text='6) I enjoy talking about: ', max_length=10, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 5, 4, 21, 26, 33, 662941, tzinfo=utc))),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('quiz_about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='quizsetup',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 21, 26, 33, 661940, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wordlesetup',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 21, 26, 33, 661940, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='TmmaSetup',
        ),
    ]
