# Generated by Django 4.0.3 on 2022-05-05 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_setup', '0010_ttmasetup_alter_quizsetup_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlesetup',
            name='qq1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wordlesetup',
            name='qq2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wordlesetup',
            name='qq3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wordlesetup',
            name='qq4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wordlesetup',
            name='qq5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quizsetup',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 19, 40, 7, 451612, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ttmasetup',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 19, 40, 7, 452813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wordlesetup',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 19, 40, 7, 451612, tzinfo=utc)),
        ),
    ]
