# Generated by Django 4.0.3 on 2022-04-29 08:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name': 'Hobby', 'verbose_name_plural': 'Hobbies'},
        ),
        migrations.AlterField(
            model_name='hobby',
            name='hobby_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hobbylist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hobbylist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 8, 24, 26, 556336, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='allUsers',
        ),
    ]
