# Generated by Django 4.0.3 on 2022-04-29 08:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0002_alter_hobby_options_alter_hobby_hobby_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbylist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 8, 26, 25, 911287, tzinfo=utc)),
        ),
    ]
