# Generated by Django 4.0.3 on 2022-04-29 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0003_alter_hobbylist_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hobbylist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 8, 32, 37, 649633, tzinfo=utc)),
        ),
    ]
