# Generated by Django 4.0.3 on 2022-04-29 14:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0004_hobby_updated_alter_hobbylist_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobby.hobbylist'),
        ),
        migrations.AlterField(
            model_name='hobbylist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 14, 37, 48, 708957, tzinfo=utc)),
        ),
    ]
