# Generated by Django 4.0.3 on 2022-04-30 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0005_alter_hobby_hobby_name_alter_hobbylist_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbylist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 12, 37, 48, 546302, tzinfo=utc)),
        ),
    ]
