# Generated by Django 2.2.12 on 2022-06-13 20:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0012_auto_20220613_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbylist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 20, 6, 22, 854715, tzinfo=utc)),
        ),
    ]
