# Generated by Django 4.0.3 on 2022-05-04 21:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0014_alter_hobbylist_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbylist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 21, 26, 33, 659940, tzinfo=utc)),
        ),
    ]
