# Generated by Django 2.2.12 on 2022-06-13 20:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 13, 20, 6, 22, 858600, tzinfo=utc), null=True),
        ),
    ]
