# Generated by Django 4.0.3 on 2022-04-27 19:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giver', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=40, null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 4, 27, 19, 47, 18, 329856, tzinfo=utc))),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
