# Generated by Django 4.0.3 on 2022-04-27 20:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('compliment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 20, 27, 53, 309589, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='compliment',
            name='receiver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
