# Generated by Django 4.0.3 on 2022-04-29 08:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('compliment', '0004_alter_compliment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 8, 26, 25, 909287, tzinfo=utc)),
        ),
    ]
