# Generated by Django 4.0.3 on 2022-04-30 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('compliment', '0007_alter_compliment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 12, 37, 48, 544303, tzinfo=utc)),
        ),
    ]
