# Generated by Django 2.2.12 on 2022-06-13 19:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('compliment', '0013_alter_compliment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 19, 54, 16, 981538, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='compliment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
