# Generated by Django 4.0.3 on 2022-05-05 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('compliment', '0017_alter_compliment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 19, 40, 7, 448598, tzinfo=utc)),
        ),
    ]
